soft-fail: true
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
  - all
output: cli
quiet: false
skip-fixes: false
skip-check:
  - CKV_AZURE_136
